---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/openjdk-buildpack
    tag: latest

inputs:
- name: openjdk-buildpack

outputs:
- name: artifactory

caches:
- path: go-build

run:
  path: openjdk-buildpack/ci/package.sh
